function obstacle = obsgen(obs)
    obstacle.Vertices = [obs(1) obs(2) obs(3); obs(1) obs(2)+obs(5) obs(3);...
                        obs(1)+obs(4) obs(2)+obs(5) obs(3); obs(1)+obs(4) obs(2) obs(3);...
                        obs(1) obs(2) obs(3)+obs(6); obs(1) obs(2)+obs(5) obs(3)+obs(6);...
                        obs(1)+obs(4) obs(2)+obs(5) obs(3)+obs(6);obs(1)+obs(4) obs(2) obs(3)+obs(6)];
end
